FROM julia:1.10.0

LABEL author="A. Mhamdi <a_mhamdi@outlook.com>"
LABEL version="latest"

#= Set ENV variables =#
ENV JULIA_DEPOT_PATH /root/.julia

WORKDIR /workspace

#= Copy datasets =#
COPY ./Codes/Julia/Datasets ./datasets/

#= Copy TOML files (deps, ver, pkg, UUID) =#
COPY ./Codes/Julia/Part-1/Project.toml ./

#= Activate environment and add IJulia kernel, Pluto and JupyterLab IDE =#
RUN julia -e 'import Pkg; Pkg.activate("."); Pkg.resolve(); Pkg.instantiate(); Pkg.precompile()'
RUN julia -e 'import Pkg; Pkg.add(["Conda", "IJulia", "Pluto"]); Pkg.precompile()'
RUN julia -e 'import Conda; Conda.add("JupyterLab")'

#= Expose ports =#
EXPOSE 1234 2468

#= Default command =#
CMD [ "julia" ]

