FROM julia:1.11

LABEL author="A. Mhamdi <a_mhamdi@outlook.com>"
LABEL version="latest"

# Set ENV variables and working directory
ENV JULIA_DEPOT_PATH=/root/.julia
WORKDIR /workspace

# Copy the entire directory content
COPY ./Codes/Julia/Part-3/. ./

# Execute the script
RUN sh -x script.sh

# Install packages
RUN julia -e 'import Pkg; Pkg.add(["Conda", "IJulia", "Pluto"]); Pkg.precompile(); Pkg.resolve()'
RUN julia -e 'import Conda; Conda.add("JupyterLab")'

# Expose ports
EXPOSE 1234 2468

# Default command
CMD ["julia"]

