FROM julia:1.11.1

LABEL author="A. Mhamdi <a_mhamdi@outlook.com>"
LABEL version="latest"

#= Set ENV variables =#
ENV JULIA_DEPOT_PATH=/root/.julia

WORKDIR /workspace

#= Copy datasets =#
COPY ./Codes/Julia/Datasets ./Datasets/

#= Copy TOML files (deps, ver, pkg, UUID) =#
COPY ./Codes/Julia/Part-1/Project.toml .

#= Activate environment and add IJulia kernel and JupyterLab IDE =#
RUN julia -e 'import Pkg; Pkg.activate("."); Pkg.instantiate(); Pkg.precompile(); Pkg.resolve()'
RUN julia -e 'import Pkg; Pkg.add(["Conda", "IJulia"]); Pkg.precompile(); Pkg.resolve()'
RUN julia -e 'import Conda; Conda.add("JupyterLab")'

#= Expose ports =#
EXPOSE 1234 2468

#= Default command =#
CMD [ "julia" ]

