# Stage 1: Builder stage
FROM julia:1.11-bookworm as builder

# Set ENV variables and working directory
ENV JULIA_DEPOT_PATH=/root/.julia
WORKDIR /workspace

# Copy the entire directory content
COPY ./Codes/Julia/Part-3/. ./

# Execute the script
RUN sh -x script.sh

# Install packages
RUN julia -e 'import Pkg; Pkg.add(["Conda", "IJulia", "Pluto"]); Pkg.precompile(); Pkg.resolve()'
RUN julia -e 'import Conda; Conda.add("JupyterLab")'

# Stage 2: Runner stage
FROM julia:1.11-bookworm as runner

LABEL author="A. Mhamdi <a_mhamdi@outlook.com>"
LABEL version="latest"

# Set ENV variables and working directory
ENV JULIA_DEPOT_PATH=/root/.julia
WORKDIR /workspace

# Copy built Julia environment from builder stage
COPY --from=builder /root/.julia /root/.julia
COPY --from=builder /workspace/ .

# Expose ports
EXPOSE 1234 2468

# Default command
CMD ["julia"]

